name: test-the-app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v3"
      - name: Setup Node-Environment
        uses: "actions/setup-node@v3"
        with:
          node-version: '16'
      - name: Install mocha
        run: npm install -g mocha
      - name: Test web application
        run: |
          npm test
          npm build